### ISSUE TITLE
Question: storybook and testing

### ISSUE THREAD

**Issue by haishengwu-okta** [oktadeveloper/react-odyssey#19]
Are we interested at incorporate https://storybook.js.org/docs/testing/react-ui-testing/

**Comment by ggreer** [comment]
If you want example usages and a hot loading demo, we have a very basic version of that in `yarn demo`.

If you make a PR that replaces our poor man's demo with storybooks, I'll gladly merge it. That said, I don't think unit testing of these components is useful. They have no internal state. They're just components that output boilerplate markup. The tests would basically be copy-pasting that markup.

**Comment by ggreer** [comment]
This is now solved with React-cosmos. Run `yarn demo` to get the equivalent of storybooks.
